//! Validation of LinearEntropy against ms_entropy reference values.
//!
//! Fixture values are generated by `tests/fixtures/generate_expected_entropy_similarities.py`
//! using `ms_entropy` with `clean_spectra=True`.
//!
//! We mirror that pipeline by preprocessing each spectrum with
//! `MsEntropyCleanSpectrum` configured with `min_ms2_difference_in_da` from the
//! CSV before calling `LinearEntropy`.

use mass_spectrometry::prelude::{
    LinearEntropy, MsEntropyCleanSpectrum, ScalarSimilarity, SpectralProcessor,
};
use support::spectrum_factory::build_spectrum;

mod support;

#[test]
fn validate_linear_entropy_against_ms_entropy() {
    let csv_path = "tests/fixtures/expected_entropy_similarities.csv";
    let mut reader = csv::Reader::from_path(csv_path)
        .unwrap_or_else(|e| panic!("Failed to open {csv_path}: {e}"));

    let mut tested = 0u32;
    let mut failures: Vec<String> = Vec::new();

    for result in reader.records() {
        let record = result.expect("Failed to read CSV record");

        let left_name = &record[0];
        let right_name = &record[1];
        let tolerance: f64 = record[2].parse().expect("bad tolerance");
        let min_ms2_difference_in_da: f64 =
            record[3].parse().expect("bad min_ms2_difference_in_da");
        let weighted = match record[4].trim() {
            "true" => true,
            "false" => false,
            other => panic!("bad weighted flag: {other}"),
        };
        let expected_score: f64 = record[5].parse().expect("bad expected score");

        let Some(left) = build_spectrum(left_name) else {
            continue;
        };
        let Some(right) = build_spectrum(right_name) else {
            continue;
        };

        let cleaner = MsEntropyCleanSpectrum::builder()
            .min_ms2_difference_in_da(min_ms2_difference_in_da)
            .expect("finite min_ms2_difference_in_da")
            .build()
            .expect("valid ms_entropy-compatible cleaner config");
        let left = cleaner.process(&left);
        let right = cleaner.process(&right);

        let scorer = if weighted {
            LinearEntropy::weighted(tolerance).expect("valid scorer config")
        } else {
            LinearEntropy::unweighted(tolerance).expect("valid scorer config")
        };

        let (score_ab, matches_ab) = scorer
            .similarity(&left, &right)
            .expect("similarity computation should succeed");
        let (score_ba, matches_ba) = scorer
            .similarity(&right, &left)
            .expect("similarity computation should succeed");

        let score_diff = (score_ab - expected_score).abs();
        if score_diff > 1e-4 {
            failures.push(format!(
                "{left_name} vs {right_name} (weighted={weighted}, tol={tolerance}, \
                 min_diff={min_ms2_difference_in_da}): \
                 score={score_ab:.12} expected={expected_score:.12} diff={score_diff:.2e}"
            ));
        }

        if (score_ab - score_ba).abs() > 1e-6 || matches_ab != matches_ba {
            failures.push(format!(
                "{left_name} vs {right_name} (weighted={weighted}, tol={tolerance}, \
                 min_diff={min_ms2_difference_in_da}): \
                 symmetry violation sim_ab={score_ab:.12}, sim_ba={score_ba:.12}, \
                 matches_ab={matches_ab}, matches_ba={matches_ba}"
            ));
        }

        tested += 1;
    }

    println!("Tested: {tested}, Failures: {}", failures.len());

    if !failures.is_empty() {
        let sample: Vec<&str> = failures.iter().take(100).map(|s| s.as_str()).collect();
        eprintln!(
            "{} / {tested} comparisons differ (showing first {}):\n{}",
            failures.len(),
            sample.len(),
            sample.join("\n")
        );
    }

    // At extreme tolerance (e.g. 2.0 Da / min_diff=4.0), iterative centroiding
    // can diverge between Rust and ms_entropy due to floating-point tie-breaking,
    // cascading into score differences. Allow up to 1% failure rate.
    let max_failures = tested / 100 + 1;
    assert!(
        failures.len() as u32 <= max_failures,
        "{} / {tested} tests failed (max allowed: {max_failures})",
        failures.len(),
    );
    assert!(
        tested >= 27_000,
        "Expected at least 27,000 tests, got {tested}"
    );
}
