//! Validation of `MsEntropyCleanSpectrum::process()` against ms_entropy's
//! `clean_spectrum()` reference output.
//!
//! Fixture values are generated by `tests/fixtures/generate_expected_entropy_similarities.py`.
//! Each row contains a spectrum name, the `min_ms2_difference_in_da` used, and
//! the expected cleaned peaks (mz:intensity pairs).

use mass_spectrometry::prelude::{MsEntropyCleanSpectrum, SpectralProcessor, Spectrum};
use support::spectrum_factory::build_spectrum;

mod support;

#[test]
fn validate_clean_spectrum_against_ms_entropy() {
    let csv_path = "tests/fixtures/expected_cleaned_spectra.csv";
    let mut reader = csv::Reader::from_path(csv_path)
        .unwrap_or_else(|e| panic!("Failed to open {csv_path}: {e}"));

    let mut tested = 0u32;
    let mut failures: Vec<String> = Vec::new();

    for result in reader.records() {
        let record = result.expect("Failed to read CSV record");

        let name = &record[0];
        let min_ms2_difference_in_da: f64 =
            record[1].parse().expect("bad min_ms2_difference_in_da");
        let expected_num_peaks: usize = record[2].parse().expect("bad num_peaks");
        let peaks_str = &record[3];

        let Some(spectrum) = build_spectrum(name) else {
            continue;
        };

        let cleaner = MsEntropyCleanSpectrum::builder()
            .min_ms2_difference_in_da(min_ms2_difference_in_da)
            .expect("finite min_ms2_difference_in_da")
            .build()
            .expect("valid cleaner config");

        let cleaned = cleaner.process(&spectrum);
        let actual_peaks: Vec<(f64, f64)> = cleaned.peaks().collect();

        let expected_peaks: Vec<(f64, f64)> = if peaks_str.is_empty() {
            Vec::new()
        } else {
            peaks_str
                .split(';')
                .map(|pair| {
                    let mut parts = pair.split(':');
                    let mz: f64 = parts.next().expect("missing mz").parse().expect("bad mz");
                    let intensity: f64 = parts
                        .next()
                        .expect("missing intensity")
                        .parse()
                        .expect("bad intensity");
                    (mz, intensity)
                })
                .collect()
        };

        if actual_peaks.len() != expected_num_peaks {
            failures.push(format!(
                "{name} (min_diff={min_ms2_difference_in_da}): peak count mismatch: \
                 got {} expected {expected_num_peaks}",
                actual_peaks.len()
            ));
            tested += 1;
            continue;
        }

        if actual_peaks.len() != expected_peaks.len() {
            failures.push(format!(
                "{name} (min_diff={min_ms2_difference_in_da}): parsed peak count mismatch: \
                 actual {} vs parsed expected {}",
                actual_peaks.len(),
                expected_peaks.len()
            ));
            tested += 1;
            continue;
        }

        for (i, (actual, expected)) in actual_peaks.iter().zip(expected_peaks.iter()).enumerate() {
            let mz_diff = (actual.0 - expected.0).abs();
            let int_diff = (actual.1 - expected.1).abs();
            // Use 2e-4 for mz: f32 ULP at mz≈1827 is ~1.22e-4, so 1e-4
            // is too tight when centroiding promotes f32→f64 intermediate values.
            if mz_diff > 2e-4 || int_diff > 1e-6 {
                failures.push(format!(
                    "{name} (min_diff={min_ms2_difference_in_da}): peak {i} mismatch: \
                     mz={:.12} expected={:.12} (diff={mz_diff:.2e}), \
                     int={:.12} expected={:.12} (diff={int_diff:.2e})",
                    actual.0, expected.0, actual.1, expected.1
                ));
                break;
            }
        }

        tested += 1;
    }

    println!("Tested: {tested}, Failures: {}", failures.len());

    if !failures.is_empty() {
        let sample: Vec<&str> = failures.iter().take(100).map(|s| s.as_str()).collect();
        eprintln!(
            "{} / {tested} cleaning checks differ (showing first {}):\n{}",
            failures.len(),
            sample.len(),
            sample.join("\n")
        );
    }

    // At extreme min_ms2_difference_in_da (e.g. 4.0 Da), iterative centroiding
    // can diverge between implementations due to floating-point tie-breaking in
    // intensity sort order. Allow up to 1% failure rate for these edge cases.
    let max_failures = tested / 100 + 1;
    assert!(
        failures.len() as u32 <= max_failures,
        "{} / {tested} tests failed (max allowed: {max_failures})",
        failures.len(),
    );
    assert!(tested >= 350, "Expected at least 350 tests, got {tested}");
}
