//! Validation of LinearEntropy against ms_entropy reference values.
//!
//! Fixture values are generated by `tests/fixtures/generate_expected_entropy_similarities.py`
//! using `ms_entropy` with `clean_spectra=True`.
//!
//! We mirror that pipeline by preprocessing each spectrum with
//! `MsEntropyCleanSpectrum` configured with `min_ms2_difference_in_da = 2*tolerance`
//! before calling `LinearEntropy`.

use mass_spectrometry::prelude::{
    LinearEntropy, MsEntropyCleanSpectrum, ScalarSimilarity, SpectralProcessor,
};
use support::spectrum_factory::build_spectrum;

mod support;

#[test]
fn validate_linear_entropy_against_ms_entropy() {
    let csv_path = "tests/fixtures/expected_entropy_similarities.csv";
    let mut reader = csv::Reader::from_path(csv_path)
        .unwrap_or_else(|e| panic!("Failed to open {csv_path}: {e}"));

    let mut tested = 0u32;
    let mut failures: Vec<String> = Vec::new();

    for result in reader.records() {
        let record = result.expect("Failed to read CSV record");

        let left_name = &record[0];
        let right_name = &record[1];
        let tolerance: f32 = record[2].parse().expect("bad tolerance");
        let weighted = match record[3].trim() {
            "true" => true,
            "false" => false,
            other => panic!("bad weighted flag: {other}"),
        };
        let expected_score: f64 = record[4].parse().expect("bad expected score");

        let Some(left) = build_spectrum(left_name) else {
            continue;
        };
        let Some(right) = build_spectrum(right_name) else {
            continue;
        };

        let cleaner = MsEntropyCleanSpectrum::<f32>::builder()
            .min_ms2_difference_in_da(2.0 * tolerance)
            .expect("finite min_ms2_difference_in_da")
            .build()
            .expect("valid ms_entropy-compatible cleaner config");
        let left = cleaner.process(&left);
        let right = cleaner.process(&right);

        let scorer = if weighted {
            LinearEntropy::weighted(tolerance).expect("valid scorer config")
        } else {
            LinearEntropy::unweighted(tolerance).expect("valid scorer config")
        };

        let (score_ab, matches_ab) = scorer
            .similarity(&left, &right)
            .expect("similarity computation should succeed");
        let (score_ba, matches_ba) = scorer
            .similarity(&right, &left)
            .expect("similarity computation should succeed");

        let score_ab_f64 = score_ab as f64;
        let score_diff = (score_ab_f64 - expected_score).abs();
        if score_diff > 1e-4 {
            failures.push(format!(
                "{left_name} vs {right_name} (weighted={weighted}, tol={tolerance}): \
                 score={score_ab_f64:.12} expected={expected_score:.12} diff={score_diff:.2e}"
            ));
        }

        if (score_ab as f64 - score_ba as f64).abs() > 1e-6 || matches_ab != matches_ba {
            failures.push(format!(
                "{left_name} vs {right_name} (weighted={weighted}, tol={tolerance}): \
                 symmetry violation sim_ab={score_ab:.12}, sim_ba={score_ba:.12}, \
                 matches_ab={matches_ab}, matches_ba={matches_ba}"
            ));
        }

        tested += 1;
    }

    println!("Tested: {tested}, Failures: {}", failures.len());

    if !failures.is_empty() {
        let sample: Vec<&str> = failures.iter().take(100).map(|s| s.as_str()).collect();
        panic!(
            "{} / {tested} tests failed (showing first {}):\n{}",
            failures.len(),
            sample.len(),
            sample.join("\n")
        );
    }

    assert!(tested > 0, "No tests were run");
}
