//! Comprehensive validation of ExactCosine against matchms CosineHungarian.
//!
//! Reads expected similarities from tests/fixtures/expected_similarities.csv
//! (generated by validate_matchms.py) and validates each against our Rust
//! implementation across multiple parameter sets.

use mass_spectrometry::prelude::*;
use support::spectrum_factory::build_spectrum;

mod support;

#[test]
fn validate_against_matchms() {
    let csv_path = "tests/fixtures/expected_similarities.csv";
    let mut reader = csv::Reader::from_path(csv_path)
        .unwrap_or_else(|e| panic!("Failed to open {csv_path}: {e}"));

    let mut tested = 0u32;
    let mut skipped = 0u32;
    let mut failures: Vec<String> = Vec::new();

    for result in reader.records() {
        let record = result.expect("Failed to read CSV record");

        let left_name = &record[0];
        let right_name = &record[1];
        let tolerance: f32 = record[2].parse().expect("bad tolerance");
        let mz_power: f32 = record[3].parse().expect("bad mz_power");
        let intensity_power: f32 = record[4].parse().expect("bad intensity_power");
        let expected_score: f64 = record[5].parse().expect("bad score");
        let expected_matches: usize = record[6].parse().expect("bad matches");

        let left = match build_spectrum(left_name) {
            Some(s) => s,
            None => {
                skipped += 1;
                continue;
            }
        };
        let right = match build_spectrum(right_name) {
            Some(s) => s,
            None => {
                skipped += 1;
                continue;
            }
        };

        let cosine =
            ExactCosine::new(mz_power, intensity_power, tolerance).expect("valid scorer config");
        let (score, matches) = cosine
            .similarity(&left, &right)
            .expect("similarity computation should succeed");

        let score_diff = (score as f64 - expected_score).abs();
        // Allow 1e-4 tolerance: for very large spectra (5000+ peaks) with
        // wide mz_tolerance, the LAP solver may find a slightly suboptimal
        // assignment compared to matchms's scipy.optimize.linear_sum_assignment.
        let score_ok = score_diff < 1e-4;
        // matchms CosineHungarian over-counts matches: it reports
        // min(|unique_left_with_edges|, |unique_right_with_edges|) which
        // includes phantom (non-within-tolerance) assignments from the
        // Hungarian algorithm. Our count is the true bipartite matching
        // size, so matches <= expected_matches.
        let matches_ok = matches <= expected_matches;

        if !score_ok || !matches_ok {
            failures.push(format!(
                "{left_name} vs {right_name} (tol={tolerance}, mz_pow={mz_power}, int_pow={intensity_power}): \
                 score={score:.12} expected={expected_score:.12} (diff={score_diff:.2e}), \
                 matches={matches} expected={expected_matches}"
            ));
        }

        tested += 1;
    }

    println!(
        "Tested: {tested}, Skipped: {skipped}, Failures: {}",
        failures.len()
    );

    if !failures.is_empty() {
        let sample: Vec<&str> = failures.iter().take(100).map(|s| s.as_str()).collect();
        panic!(
            "{} / {tested} tests failed (showing first {}):\n{}",
            failures.len(),
            sample.len(),
            sample.join("\n")
        );
    }

    assert!(tested > 0, "No tests were run");
}
