use mass_spectrometry::prelude::*;

/// Build a `GenericSpectrum<f32, f32>` by compound name.
pub fn build_spectrum(name: &str) -> Option<GenericSpectrum<f32, f32>> {
    Some(match name {
        "acephate" => GenericSpectrum::acephate(),
        "acetyl_coenzyme_a" => GenericSpectrum::acetyl_coenzyme_a(),
        "adenine" => GenericSpectrum::adenine(),
        "adenosine" => GenericSpectrum::adenosine(),
        "adenosine_5_diphosphate" => GenericSpectrum::adenosine_5_diphosphate(),
        "adenosine_5_monophosphate" => GenericSpectrum::adenosine_5_monophosphate(),
        "alanine" => GenericSpectrum::alanine(),
        "arachidic_acid" => GenericSpectrum::arachidic_acid(),
        "arachidonic_acid" => GenericSpectrum::arachidonic_acid(),
        "arginine" => GenericSpectrum::arginine(),
        "ascorbic_acid" => GenericSpectrum::ascorbic_acid(),
        "aspartic_acid" => GenericSpectrum::aspartic_acid(),
        "aspirin" => GenericSpectrum::aspirin(),
        "avermectin" => GenericSpectrum::avermectin(),
        "biotin" => GenericSpectrum::biotin(),
        "boscalid" => GenericSpectrum::boscalid(),
        "chlorantraniliprole" => GenericSpectrum::chlorantraniliprole(),
        "chlorfluazuron" => GenericSpectrum::chlorfluazuron(),
        "chlorotoluron" => GenericSpectrum::chlorotoluron(),
        "citric_acid" => GenericSpectrum::citric_acid(),
        "clothianidin" => GenericSpectrum::clothianidin(),
        "cocaine" => GenericSpectrum::cocaine(),
        "cyazofamid" => GenericSpectrum::cyazofamid(),
        "cymoxanil" => GenericSpectrum::cymoxanil(),
        "cysteine" => GenericSpectrum::cysteine(),
        "cytidine" => GenericSpectrum::cytidine(),
        "cytidine_5_diphosphate" => GenericSpectrum::cytidine_5_diphosphate(),
        "cytidine_5_triphosphate" => GenericSpectrum::cytidine_5_triphosphate(),
        "desmosterol" => GenericSpectrum::desmosterol(),
        "diflubenzuron" => GenericSpectrum::diflubenzuron(),
        "dihydrosphingosine" => GenericSpectrum::dihydrosphingosine(),
        "diniconazole" => GenericSpectrum::diniconazole(),
        "dinotefuran" => GenericSpectrum::dinotefuran(),
        "diuron" => GenericSpectrum::diuron(),
        "doramectin" => GenericSpectrum::doramectin(),
        "elaidic_acid" => GenericSpectrum::elaidic_acid(),
        "epimeloscine" => GenericSpectrum::epimeloscine(),
        "eprinomectin" => GenericSpectrum::eprinomectin(),
        "ethiprole" => GenericSpectrum::ethiprole(),
        "ethirimol" => GenericSpectrum::ethirimol(),
        "fipronil" => GenericSpectrum::fipronil(),
        "flonicamid" => GenericSpectrum::flonicamid(),
        "fluazinam" => GenericSpectrum::fluazinam(),
        "fludioxinil" => GenericSpectrum::fludioxinil(),
        "flufenoxuron" => GenericSpectrum::flufenoxuron(),
        "fluometuron" => GenericSpectrum::fluometuron(),
        "flutolanil" => GenericSpectrum::flutolanil(),
        "folic_acid" => GenericSpectrum::folic_acid(),
        "forchlorfenuron" => GenericSpectrum::forchlorfenuron(),
        "fuberidazole" => GenericSpectrum::fuberidazole(),
        "glucose" => GenericSpectrum::glucose(),
        "halofenozide" => GenericSpectrum::halofenozide(),
        "hexaflumuron" => GenericSpectrum::hexaflumuron(),
        "hydramethylnon" => GenericSpectrum::hydramethylnon(),
        "hydroxy_cholesterol" | "hydroxycholesterol" => GenericSpectrum::hydroxy_cholesterol(),
        "ivermectin" => GenericSpectrum::ivermectin(),
        "lufenuron" => GenericSpectrum::lufenuron(),
        "metaflumizone" => GenericSpectrum::metaflumizone(),
        "n1_2_dierucoyl_sn_glycero_3_phosphocholine" => {
            GenericSpectrum::n1_2_dierucoyl_sn_glycero_3_phosphocholine()
        }
        "n1_2_dioleoyl_rac_glycerol" => GenericSpectrum::n1_2_dioleoyl_rac_glycerol(),
        "n1_oleoyl_sn_glycero_3_phosphocholine" => {
            GenericSpectrum::n1_oleoyl_sn_glycero_3_phosphocholine()
        }
        "n1_palmitoyl_sn_glycero_3_phosphocholine" => {
            GenericSpectrum::n1_palmitoyl_sn_glycero_3_phosphocholine()
        }
        "n2_5_dihydroxybenzoic_acid" => GenericSpectrum::n2_5_dihydroxybenzoic_acid(),
        "n4_aminobenzoic_acid" => GenericSpectrum::n4_aminobenzoic_acid(),
        "n4_cholesten_3_one" => GenericSpectrum::n4_cholesten_3_one(),
        "neburon" => GenericSpectrum::neburon(),
        "nitenpyram" => GenericSpectrum::nitenpyram(),
        "novaluron" => GenericSpectrum::novaluron(),
        "phenylalanine" => GenericSpectrum::phenylalanine(),
        "prothioconazole" => GenericSpectrum::prothioconazole(),
        "pymetrozine" => GenericSpectrum::pymetrozine(),
        "pyrimethanil" => GenericSpectrum::pyrimethanil(),
        "salicin" => GenericSpectrum::salicin(),
        "sulfentrazone" => GenericSpectrum::sulfentrazone(),
        "tebufenozide" => GenericSpectrum::tebufenozide(),
        "teflubenzuron" => GenericSpectrum::teflubenzuron(),
        "thidiazuron" => GenericSpectrum::thidiazuron(),
        "thiophanate" => GenericSpectrum::thiophanate(),
        "triadimefon" => GenericSpectrum::triadimefon(),
        "triflumuron" => GenericSpectrum::triflumuron(),
        _ => return None,
    })
}
